# Generated by Django 3.1 on 2020-10-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_auto_20201007_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='id',
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
