# Generated by Django 3.1 on 2020-10-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20201007_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='month_year',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
