# Generated by Django 3.1 on 2020-10-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_date_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='quartile',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='date',
            name='trimester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
