# Generated by Django 3.1 on 2020-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.FileField(upload_to='files/filebackup'),
        ),
    ]
