# Generated by Django 3.1 on 2020-09-30 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_auto_20200930_1906'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax', models.FloatField(null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgetuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('repetir', models.IntegerField(null=True)),
                ('Revenue_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.faturamentoorigem')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('amount2', models.FloatField(default=0, null=True)),
                ('amount3', models.FloatField(default=0, null=True)),
                ('amount4', models.FloatField(default=0, null=True)),
                ('amount5', models.FloatField(default=0, null=True)),
                ('amount6', models.FloatField(default=0, null=True)),
                ('amount7', models.FloatField(default=0, null=True)),
                ('amount8', models.FloatField(default=0, null=True)),
                ('amount9', models.FloatField(default=0, null=True)),
                ('amount10', models.FloatField(default=0, null=True)),
                ('amount11', models.FloatField(default=0, null=True)),
                ('amount12', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0, null=True)),
                ('amount2', models.FloatField(default=0, null=True)),
                ('amount3', models.FloatField(default=0, null=True)),
                ('amount4', models.FloatField(default=0, null=True)),
                ('amount5', models.FloatField(default=0, null=True)),
                ('amount6', models.FloatField(default=0, null=True)),
                ('amount7', models.FloatField(default=0, null=True)),
                ('amount8', models.FloatField(default=0, null=True)),
                ('amount9', models.FloatField(default=0, null=True)),
                ('amount10', models.FloatField(default=0, null=True)),
                ('amount11', models.FloatField(default=0, null=True)),
                ('amount12', models.FloatField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.budget')),
                ('faturamentoorigem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.faturamentoorigem')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('repetir', models.IntegerField(null=True)),
                ('expenseType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.expensetype')),
            ],
            managers=[
                ('date_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
