# Generated by Django 3.1 on 2020-10-01 01:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='revenue',
            managers=[
                ('date_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
