# Generated by Django 3.1 on 2020-10-01 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_auto_20201001_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 20, 33, 43, 404331)),
        ),
    ]
