# Generated by Django 3.1 on 2020-10-01 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_auto_20201001_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 1, 23, 35, 33, 660164, tzinfo=utc)),
        ),
    ]
