# Generated by Django 3.1 on 2020-10-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0011_auto_20201002_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='repetir',
            field=models.CharField(choices=[('1', 'Não repetir'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '6'), ('8', '7'), ('9', '8'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='repetir',
            field=models.CharField(blank=True, choices=[('1', 'Não repetir'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '6'), ('8', '7'), ('9', '8'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=30, null=True),
        ),
    ]
