# Generated by Django 3.1 on 2020-10-07 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0002_auto_20201007_0849'),
        ('tasks', '0002_auto_20200930_1906'),
        ('budgets', '0012_auto_20201002_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('repetir', models.CharField(blank=True, choices=[('1', 'Não repetir'), ('2', '1'), ('3', '2'), ('4', '3'), ('5', '4'), ('6', '5'), ('7', '6'), ('8', '7'), ('9', '8'), ('10', '9'), ('11', '10'), ('12', '11'), ('13', '12')], max_length=30, null=True)),
                ('Revenue_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.faturamentoorigem')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dates.date')),
            ],
            managers=[
                ('date_obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
