# Generated by Django 3.1 on 2020-10-07 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0013_revenue2'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='revenue2',
            managers=[
            ],
        ),
    ]
