# Generated by Django 3.1 on 2020-10-07 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0003_auto_20201007_1625'),
        ('budgets', '0015_auto_20201007_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue2',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dates.date'),
        ),
    ]
