# Generated by Django 3.1 on 2020-10-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dates', '0004_date_month_year'),
        ('budgets', '0016_auto_20201007_1647'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='expense',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='revenue',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dates.date'),
        ),
    ]
