# Generated by Django 3.1 on 2020-10-06 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201006_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sales_comission',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
